// Component exports for easier importing
export { default as Hero } from './Hero'
export { default as About } from './About'
export { default as Education } from './Education'
export { default as Experience } from './Experience'
export { default as Skills } from './Skills'
export { default as Projects } from './Projects'
export { default as Achievements } from './Achievements'
export { default as ProfessionalDevelopment } from './ProfessionalDevelopment'
export { default as Contact } from './Contact'
export { default as Navigation } from './Navigation'
export { default as ImpactHighlights } from './ImpactHighlights'
